
CREATE OR REPLACE FUNCTION public.lril_detect_country_from_text(p_text text)
RETURNS text
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH t AS (SELECT lower(coalesce(p_text,'')) AS s)
  SELECT iso3 FROM (
    SELECT 'ZAF' iso3 FROM t WHERE s ~* '\m(south africa|johannesburg|cape town|durban|pretoria|soweto|alexandra|hillbrow|khayelitsha|tembisa|mamelodi|dudula|gauteng|kwazulu)\M'
    UNION ALL SELECT 'NGA' FROM t WHERE s ~* '\m(nigeria|lagos|abuja|kano|kaduna|maiduguri|port harcourt|ibadan|jos|borno)\M'
    UNION ALL SELECT 'GHA' FROM t WHERE s ~* '\m(ghana|accra|kumasi|dumsor|tema|takoradi|tamale)\M'
    UNION ALL SELECT 'KEN' FROM t WHERE s ~* '\m(kenya|nairobi|mombasa|kisumu|kibera|mathare|eldoret)\M'
    UNION ALL SELECT 'ETH' FROM t WHERE s ~* '\m(ethiopia|addis ababa|tigray|mekelle|amhara|oromia)\M'
    UNION ALL SELECT 'SDN' FROM t WHERE s ~* '\m(sudan|khartoum|omdurman|darfur|el fasher|rsf)\M'
    UNION ALL SELECT 'COD' FROM t WHERE s ~* '\m(dr congo|drc|kinshasa|goma|bunia|north kivu|south kivu|m23)\M'
    UNION ALL SELECT 'SOM' FROM t WHERE s ~* '\m(somalia|mogadishu|al-shabaab|al shabaab|kismayo)\M'
    UNION ALL SELECT 'ZWE' FROM t WHERE s ~* '\m(zimbabwe|harare|bulawayo)\M'
    UNION ALL SELECT 'UGA' FROM t WHERE s ~* '\m(uganda|kampala|entebbe)\M'
    UNION ALL SELECT 'CIV' FROM t WHERE s ~* '\m(ivory coast|côte d''ivoire|abidjan|yamoussoukro)\M'
    UNION ALL SELECT 'SEN' FROM t WHERE s ~* '\m(senegal|dakar)\M'
    UNION ALL SELECT 'MLI' FROM t WHERE s ~* '\m(mali|bamako|gao|timbuktu)\M'
    UNION ALL SELECT 'BFA' FROM t WHERE s ~* '\m(burkina faso|ouagadougou)\M'
    UNION ALL SELECT 'NER' FROM t WHERE s ~* '\m(niger\M|niamey)\M'
    UNION ALL SELECT 'TCD' FROM t WHERE s ~* '\m(chad|n''djamena|ndjamena)\M'
    UNION ALL SELECT 'CMR' FROM t WHERE s ~* '\m(cameroon|yaoundé|yaounde|douala)\M'
    UNION ALL SELECT 'EGY' FROM t WHERE s ~* '\m(egypt|cairo|alexandria|giza)\M'
    UNION ALL SELECT 'MAR' FROM t WHERE s ~* '\m(morocco|rabat|casablanca|marrakech)\M'
    UNION ALL SELECT 'DZA' FROM t WHERE s ~* '\m(algeria|algiers)\M'
    UNION ALL SELECT 'TUN' FROM t WHERE s ~* '\m(tunisia|tunis)\M'
    UNION ALL SELECT 'LBY' FROM t WHERE s ~* '\m(libya|tripoli|benghazi)\M'
    UNION ALL SELECT 'MOZ' FROM t WHERE s ~* '\m(mozambique|maputo|cabo delgado)\M'
    UNION ALL SELECT 'AGO' FROM t WHERE s ~* '\m(angola|luanda)\M'
    UNION ALL SELECT 'IND' FROM t WHERE s ~* '\m(india\M|new delhi|mumbai|kolkata|chennai|bengaluru|bangalore|hyderabad|dharavi)\M'
    UNION ALL SELECT 'PAK' FROM t WHERE s ~* '\m(pakistan|islamabad|karachi|lahore|peshawar|lyari)\M'
    UNION ALL SELECT 'BGD' FROM t WHERE s ~* '\m(bangladesh|dhaka|chittagong|cox.s bazar)\M'
    UNION ALL SELECT 'AFG' FROM t WHERE s ~* '\m(afghanistan|kabul|kandahar|herat|taliban)\M'
    UNION ALL SELECT 'IRN' FROM t WHERE s ~* '\m(iran\M|tehran|isfahan|mashhad)\M'
    UNION ALL SELECT 'IRQ' FROM t WHERE s ~* '\m(iraq|baghdad|mosul|basra)\M'
    UNION ALL SELECT 'SYR' FROM t WHERE s ~* '\m(syria|damascus|aleppo|idlib)\M'
    UNION ALL SELECT 'YEM' FROM t WHERE s ~* '\m(yemen|sanaa|aden|houthi)\M'
    UNION ALL SELECT 'LBN' FROM t WHERE s ~* '\m(lebanon|beirut|tyre)\M'
    UNION ALL SELECT 'PSE' FROM t WHERE s ~* '\m(gaza|west bank|ramallah|hebron|rafah|khan younis|palestin)\M'
    UNION ALL SELECT 'ISR' FROM t WHERE s ~* '\m(israel|tel aviv|jerusalem)\M'
    UNION ALL SELECT 'TUR' FROM t WHERE s ~* '\m(turkey|türkiye|istanbul|ankara|izmir)\M'
    UNION ALL SELECT 'UKR' FROM t WHERE s ~* '\m(ukraine|kyiv|kiev|kharkiv|odesa|lviv|donetsk)\M'
    UNION ALL SELECT 'RUS' FROM t WHERE s ~* '\m(russia|moscow|saint petersburg|kremlin)\M'
    UNION ALL SELECT 'CHN' FROM t WHERE s ~* '\m(china|beijing|shanghai|guangzhou|shenzhen|wuhan)\M'
    UNION ALL SELECT 'JPN' FROM t WHERE s ~* '\m(japan|tokyo|osaka|kyoto)\M'
    UNION ALL SELECT 'KOR' FROM t WHERE s ~* '\m(south korea|seoul|busan)\M'
    UNION ALL SELECT 'PRK' FROM t WHERE s ~* '\m(north korea|pyongyang|dprk)\M'
    UNION ALL SELECT 'MMR' FROM t WHERE s ~* '\m(myanmar|burma|yangon|naypyidaw|rakhine|rohingya)\M'
    UNION ALL SELECT 'THA' FROM t WHERE s ~* '\m(thailand|bangkok)\M'
    UNION ALL SELECT 'IDN' FROM t WHERE s ~* '\m(indonesia|jakarta|surabaya|bali|sumatra)\M'
    UNION ALL SELECT 'PHL' FROM t WHERE s ~* '\m(philippines|manila|cebu|davao)\M'
    UNION ALL SELECT 'VNM' FROM t WHERE s ~* '\m(vietnam|hanoi|ho chi minh|saigon)\M'
    UNION ALL SELECT 'MEX' FROM t WHERE s ~* '\m(mexico|cdmx|guadalajara|monterrey|sinaloa|culiacan|acapulco)\M'
    UNION ALL SELECT 'BRA' FROM t WHERE s ~* '\m(brazil|brasil|rio de janeiro|sao paulo|são paulo|brasilia|salvador|favela)\M'
    UNION ALL SELECT 'ARG' FROM t WHERE s ~* '\m(argentina|buenos aires|cordoba)\M'
    UNION ALL SELECT 'COL' FROM t WHERE s ~* '\m(colombia|bogota|medellin|cali|comuna 13)\M'
    UNION ALL SELECT 'VEN' FROM t WHERE s ~* '\m(venezuela|caracas|maracaibo)\M'
    UNION ALL SELECT 'PER' FROM t WHERE s ~* '\m(peru|lima)\M'
    UNION ALL SELECT 'CHL' FROM t WHERE s ~* '\m(chile|santiago|valparaiso)\M'
    UNION ALL SELECT 'ECU' FROM t WHERE s ~* '\m(ecuador|quito|guayaquil)\M'
    UNION ALL SELECT 'HTI' FROM t WHERE s ~* '\m(haiti|port-au-prince|cite soleil|martissant)\M'
    UNION ALL SELECT 'CUB' FROM t WHERE s ~* '\m(cuba|havana)\M'
    UNION ALL SELECT 'USA' FROM t WHERE s ~* '\m(united states|u\.s\.|usa\M|new york|los angeles|chicago|texas|california|florida)\M'
    UNION ALL SELECT 'CAN' FROM t WHERE s ~* '\m(canada|toronto|montreal|vancouver|ottawa)\M'
    UNION ALL SELECT 'GBR' FROM t WHERE s ~* '\m(united kingdom|britain|london|manchester|birmingham|scotland|wales)\M'
    UNION ALL SELECT 'FRA' FROM t WHERE s ~* '\m(france\M|paris|marseille|lyon)\M'
    UNION ALL SELECT 'DEU' FROM t WHERE s ~* '\m(germany|berlin|munich|hamburg|frankfurt)\M'
    UNION ALL SELECT 'ESP' FROM t WHERE s ~* '\m(spain|madrid|barcelona)\M'
    UNION ALL SELECT 'ITA' FROM t WHERE s ~* '\m(italy|rome|milan|naples)\M'
    UNION ALL SELECT 'AUS' FROM t WHERE s ~* '\m(australia|sydney|melbourne|brisbane)\M'
    UNION ALL SELECT 'NZL' FROM t WHERE s ~* '\m(new zealand|auckland|wellington)\M'
  ) x
  ORDER BY 1
  LIMIT 1;
$$;
