
CREATE OR REPLACE FUNCTION public.lril_fips_to_iso3(p_code text)
RETURNS text LANGUAGE sql IMMUTABLE SET search_path = public AS $$
  SELECT CASE upper(coalesce(p_code,''))
    -- GDELT quirky 3-letter aliases
    WHEN 'UNI' THEN 'USA'  -- United States in GDELT v2 (or UK in some feeds; USA is more common)
    WHEN 'SOU' THEN 'ZAF'  -- South Africa
    WHEN 'NIG' THEN 'NGA'  -- Nigeria (GDELT abbrev)
    WHEN 'SPA' THEN 'ESP'  -- Spain
    WHEN 'POR' THEN 'PRT'  -- Portugal
    WHEN 'IRE' THEN 'IRL'  -- Ireland
    WHEN 'GER' THEN 'DEU'  -- Germany
    WHEN 'AUT' THEN 'AUT'  -- Austria (correct already)
    WHEN 'BAN' THEN 'BGD'  -- Bangladesh
    WHEN 'CHI' THEN 'CHN'  -- China (or Chile - CHN more common in news)
    WHEN 'MYA' THEN 'MMR'  -- Myanmar
    WHEN 'NZL' THEN 'NZL'
    WHEN 'SER' THEN 'SRB'  -- Serbia
    WHEN 'SWI' THEN 'CHE'  -- Switzerland
    WHEN 'VIE' THEN 'VNM'  -- Vietnam
    WHEN 'PHI' THEN 'PHL' WHEN 'CAM' THEN 'KHM' WHEN 'SRI' THEN 'LKA'
    WHEN 'NEW' THEN 'NZL' WHEN 'FIJ' THEN 'FJI'
    -- FIPS-10-4 2-letter
    WHEN 'GM' THEN 'DEU' WHEN 'UK' THEN 'GBR' WHEN 'EN' THEN 'GBR'
    WHEN 'FR' THEN 'FRA' WHEN 'IT' THEN 'ITA' WHEN 'SP' THEN 'ESP'
    WHEN 'PO' THEN 'PRT' WHEN 'NL' THEN 'NLD' WHEN 'BE' THEN 'BEL'
    WHEN 'SZ' THEN 'CHE' WHEN 'EZ' THEN 'CZE'
    WHEN 'PL' THEN 'POL' WHEN 'HU' THEN 'HUN' WHEN 'RO' THEN 'ROU'
    WHEN 'BU' THEN 'BGR' WHEN 'GR' THEN 'GRC' WHEN 'TU' THEN 'TUR'
    WHEN 'RS' THEN 'RUS' WHEN 'UP' THEN 'UKR' WHEN 'BO' THEN 'BLR'
    WHEN 'IS' THEN 'ISR' WHEN 'IR' THEN 'IRN' WHEN 'IZ' THEN 'IRQ'
    WHEN 'SY' THEN 'SYR' WHEN 'JO' THEN 'JOR' WHEN 'LE' THEN 'LBN'
    WHEN 'SA' THEN 'SAU' WHEN 'YE' THEN 'YEM' WHEN 'AE' THEN 'ARE'
    WHEN 'KU' THEN 'KWT' WHEN 'QA' THEN 'QAT' WHEN 'BA' THEN 'BHR'
    WHEN 'AF' THEN 'AFG' WHEN 'PK' THEN 'PAK' WHEN 'IN' THEN 'IND'
    WHEN 'BG' THEN 'BGD' WHEN 'CE' THEN 'LKA'
    WHEN 'NP' THEN 'NPL' WHEN 'BT' THEN 'BTN' WHEN 'BM' THEN 'MMR'
    WHEN 'CB' THEN 'KHM' WHEN 'LA' THEN 'LAO'
    WHEN 'TH' THEN 'THA' WHEN 'VM' THEN 'VNM' WHEN 'MY' THEN 'MYS'
    WHEN 'SN' THEN 'SGP' WHEN 'ID' THEN 'IDN' WHEN 'RP' THEN 'PHL'
    WHEN 'JA' THEN 'JPN' WHEN 'KS' THEN 'KOR'
    WHEN 'KN' THEN 'PRK' WHEN 'CH' THEN 'CHN' WHEN 'TW' THEN 'TWN'
    WHEN 'HK' THEN 'HKG' WHEN 'AS' THEN 'AUS'
    WHEN 'NZ' THEN 'NZL' WHEN 'PP' THEN 'PNG'
    WHEN 'FJ' THEN 'FJI' WHEN 'CA' THEN 'CAN'
    WHEN 'US' THEN 'USA' WHEN 'MX' THEN 'MEX' WHEN 'BR' THEN 'BRA'
    WHEN 'AR' THEN 'ARG' WHEN 'CI' THEN 'CHL' WHEN 'PE' THEN 'PER'
    WHEN 'CO' THEN 'COL' WHEN 'VE' THEN 'VEN' WHEN 'EC' THEN 'ECU'
    WHEN 'BL' THEN 'BOL' WHEN 'PA' THEN 'PRY' WHEN 'UY' THEN 'URY'
    WHEN 'CU' THEN 'CUB' WHEN 'HA' THEN 'HTI' WHEN 'DR' THEN 'DOM'
    WHEN 'JM' THEN 'JAM' WHEN 'GT' THEN 'GTM' WHEN 'HO' THEN 'HND'
    WHEN 'NU' THEN 'NIC' WHEN 'ES' THEN 'SLV' WHEN 'CS' THEN 'CRI'
    WHEN 'PM' THEN 'PAN' WHEN 'EG' THEN 'EGY' WHEN 'MO' THEN 'MAR'
    WHEN 'AG' THEN 'DZA' WHEN 'TS' THEN 'TUN' WHEN 'LY' THEN 'LBY'
    WHEN 'SU' THEN 'SDN' WHEN 'OD' THEN 'SSD' WHEN 'ET' THEN 'ETH'
    WHEN 'ER' THEN 'ERI' WHEN 'DJ' THEN 'DJI' WHEN 'SO' THEN 'SOM'
    WHEN 'KE' THEN 'KEN' WHEN 'UG' THEN 'UGA' WHEN 'TZ' THEN 'TZA'
    WHEN 'RW' THEN 'RWA' WHEN 'BY' THEN 'BDI' WHEN 'CG' THEN 'COD'
    WHEN 'CF' THEN 'COG' WHEN 'CM' THEN 'CMR' WHEN 'NI' THEN 'NGA'
    WHEN 'NG' THEN 'NER' WHEN 'CD' THEN 'TCD' WHEN 'ML' THEN 'MLI'
    WHEN 'UV' THEN 'BFA' WHEN 'IV' THEN 'CIV' WHEN 'GH' THEN 'GHA'
    WHEN 'TO' THEN 'TGO' WHEN 'BN' THEN 'BEN' WHEN 'SG' THEN 'SEN'
    WHEN 'GA' THEN 'GMB' WHEN 'GV' THEN 'GIN' WHEN 'PU' THEN 'GNB'
    WHEN 'SL' THEN 'SLE' WHEN 'LI' THEN 'LBR' WHEN 'MZ' THEN 'MOZ'
    WHEN 'AO' THEN 'AGO' WHEN 'ZA' THEN 'ZMB' WHEN 'MI' THEN 'MWI'
    WHEN 'ZI' THEN 'ZWE' WHEN 'BC' THEN 'BWA' WHEN 'WA' THEN 'NAM'
    WHEN 'SF' THEN 'ZAF' WHEN 'LT' THEN 'LSO' WHEN 'WZ' THEN 'SWZ'
    WHEN 'MA' THEN 'MDG' WHEN 'MP' THEN 'MUS' WHEN 'EI' THEN 'IRL'
    WHEN 'IC' THEN 'ISL' WHEN 'DA' THEN 'DNK' WHEN 'NO' THEN 'NOR'
    WHEN 'SW' THEN 'SWE' WHEN 'FI' THEN 'FIN'
    WHEN 'LG' THEN 'LVA' WHEN 'LH' THEN 'LTU' WHEN 'AL' THEN 'ALB'
    WHEN 'MK' THEN 'MKD' WHEN 'MJ' THEN 'MNE' WHEN 'KV' THEN 'XKX'
    WHEN 'BK' THEN 'BIH' WHEN 'HR' THEN 'HRV' WHEN 'SI' THEN 'SVN'
    WHEN 'SK' THEN 'SVK' WHEN 'AM' THEN 'ARM' WHEN 'AJ' THEN 'AZE'
    WHEN 'GG' THEN 'GEO' WHEN 'KZ' THEN 'KAZ' WHEN 'KG' THEN 'KGZ'
    WHEN 'TI' THEN 'TJK' WHEN 'TX' THEN 'TKM' WHEN 'UZ' THEN 'UZB'
    WHEN 'MD' THEN 'MDA'
    ELSE NULLIF(upper(p_code), '')
  END;
$$;

UPDATE public.aicis_local_events SET iso3_normalized = lril_fips_to_iso3(iso3);
SELECT public.lril_bridge_to_normalized();
