export const COUNTRY_NAMES: Record<string, string> = {
  AFG:"Afghanistan",AGO:"Angola",ARG:"Argentina",AUS:"Australia",BDI:"Burundi",
  BFA:"Burkina Faso",BGD:"Bangladesh",BRA:"Brazil",CAF:"Central African Republic",
  CHN:"China",COD:"DR Congo",COL:"Colombia",CMR:"Cameroon",DEU:"Germany",
  EGY:"Egypt",ETH:"Ethiopia",FRA:"France",GBR:"United Kingdom",GHA:"Ghana",
  GMB:"Gambia",GTM:"Guatemala",HTI:"Haiti",IDN:"Indonesia",IND:"India",
  IRN:"Iran",IRQ:"Iraq",ISR:"Israel",JPN:"Japan",KEN:"Kenya",KIR:"Kiribati",
  LBY:"Libya",MDG:"Madagascar",MEX:"Mexico",MLI:"Mali",MMR:"Myanmar",
  MOZ:"Mozambique",MWI:"Malawi",NER:"Niger",NGA:"Nigeria",PAK:"Pakistan",
  PER:"Peru",PHL:"Philippines",RUS:"Russia",RWA:"Rwanda",SAU:"Saudi Arabia",
  SDN:"Sudan",SEN:"Senegal",SLV:"El Salvador",SOM:"Somalia",SSD:"South Sudan",
  SYR:"Syria",TCD:"Chad",THA:"Thailand",TUR:"Turkey",TZA:"Tanzania",
  UGA:"Uganda",UKR:"Ukraine",USA:"United States",VEN:"Venezuela",VNM:"Vietnam",
  YEM:"Yemen",ZAF:"South Africa",ZMB:"Zambia",ZWE:"Zimbabwe",
  ARE:"UAE",MYS:"Malaysia",COG:"Congo",GIN:"Guinea",LBR:"Liberia",SLE:"Sierra Leone",
  TGO:"Togo",BEN:"Benin",DJI:"Djibouti",ERI:"Eritrea",GAB:"Gabon",GNQ:"Eq. Guinea",
  LSO:"Lesotho",MRT:"Mauritania",NAM:"Namibia",SWZ:"Eswatini",TUN:"Tunisia",
  MAR:"Morocco",DZA:"Algeria",LKA:"Sri Lanka",NPL:"Nepal",KHM:"Cambodia",
  LAO:"Laos",TWN:"Taiwan",KOR:"South Korea",PRK:"North Korea",MNG:"Mongolia",
  KAZ:"Kazakhstan",UZB:"Uzbekistan",TKM:"Turkmenistan",KGZ:"Kyrgyzstan",
  TJK:"Tajikistan",GEO:"Georgia",ARM:"Armenia",AZE:"Azerbaijan",JOR:"Jordan",
  LBN:"Lebanon",KWT:"Kuwait",BHR:"Bahrain",QAT:"Qatar",OMN:"Oman",
  ECU:"Ecuador",BOL:"Bolivia",PRY:"Paraguay",URY:"Uruguay",CHL:"Chile",
  CRI:"Costa Rica",PAN:"Panama",HND:"Honduras",NIC:"Nicaragua",CUB:"Cuba",
  DOM:"Dominican Republic",JAM:"Jamaica",TTO:"Trinidad & Tobago",
  CIV:"Ivory Coast",BWA:"Botswana",
};
